use_frameworks!

target 'CleanRx_Example' do
  pod 'CleanRx', :path => '../'

  target 'CleanRx_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
